spring.application.name=resume-screener
# Enable H2 Database
spring.datasource.url=jdbc:h2:mem:resumedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create tables based on our Java Models
spring.jpa.hibernate.ddl-auto=update

# Allow viewing the database in the browser
spring.h2.console.enabled=true